apiVersion: apps/v1
kind: Deployment
metadata:
  name: avnet-frontend
spec:
  selector:
    matchLabels:
      app: avnet-frontend
  template:
    metadata:
      labels:
        app: avnet-frontend
    spec:
      containers:
        - name: avnet-frontend
          image: vannisil/avnet-frontend
          ports:
            - containerPort: 3000

# ---

# kind: Service
# apiVersion: v1
# metadata:
#   name: avnet-frontend
# spec:
#   type: NodePort
#   ports:
#     - port: 3000
#       targetPort: 3000
#       protocol: TCP
#       nodePort: 32000
#   selector:
#     app: avnet-frontend
