import { useEffect, useState } from "react";
import Path from "./components/Path";
import { getAllCu } from "./utils/HandleApi";


function Home() {
    const [cu, setCu] = useState([])

    useEffect(() => {
        getAllCu(setCu)
    }, [])


    return (
        <div className="Home">
            <div className="centeredHome">
                <h1>Home</h1>
                <br></br>
                <br></br>
                <p>The main purpose of the AHEREUM application is to create and manage routes for aircraft.</p>
                <br></br>
                <p>Specifically, as a result of entering a name and a set of coordinates, a path can be generated and consequently loaded into a database.</p>
                <br></br>
                <p>As far as the latter is concerned, our choice fell on MongoDB (a nonrelational database) in which we perform the saving of JSON files that contain within them the information on all the various aircraft routes.</p>
                <br></br>
                <p>This then allows us to manage, within the application, an entire section dedicated to route simulation.
                    In fact, based on the information in the database, it goes to check the progress of the vehicle to see if it is flying over the predetermined ECUs.</p>

                <br></br><br></br>
                <h2>CONTROL UNITS:</h2>
                <p>allows you to enter the coordinates of the ECUs (latitude and longitude) and give them a name</p>
                <h2>PATH:</h2>
                <p>allows a path to be generated by defining several steps, each of which contains the coordinates of one of the previously stored ECUs</p>
                <h2>HISTORY:</h2>
                <p>contains a history of all the routes created so that, in case you want to re-execute a route that has already been saved, you only have to go back to the name under which it was stored</p>
                <h2>SIMULATOR:</h2>
                <p>this simulation allows you to run a path going to evaluate the progress of the aircraft in real time</p>
                <h2>BACKUP:</h2>
                <p>manages the saving of all JSON files containing the paths or coordinates of individual ECUs</p>
            </div>
        </div>
    );

}

export default Home